export const GET_LIST_POST = "GET_LIST_POST";
export const GET_LIST_POST_SUCCESS = "GET_LIST_POST_SUCCESS";
export const GET_LIST_POST_Detail = "GET_LIST_POST_Detail";

export const POST_LIST_POST = "POST_LIST_POST";
export const POST_LIST_POST_SUCCESS = "POST_LIST_POST_SUCCESS";

export const PUT_LIST_POST = "PUT_LIST_POST";
export const PUT_LIST_POST_SUCCESS = "PUT_LIST_POST_SUCCESS";

export const DELETE_LIST_POST = "DELETE_LIST_POST";
export const DELETE_LIST_POST_SUCCESS = "DELETE_LIST_POST_SUCCESS";
